repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: [-r, -c, .bandit.yml]
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
- repo: https://github.com/psf/black.git
  rev: 23.9.1
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==23.9.1
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: [
        --keep-mock,
        --keep-percent-format,
        --keep-runtime-typing,
        # --py38-plus,
      ]
